on:
    push:
      branches:
        - '**'
      tags:
        - 'v*'
    pull_request:
      branches:
        - 'master'
    workflow_dispatch: 
  
  name: Docker Image
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/jerson/ingress-dns
        - uses: docker/setup-qemu-action@v3
        - uses: docker/setup-buildx-action@v3
        - if: github.event_name != 'pull_request'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - id: docker_build
          uses: docker/build-push-action@v5
          with:
            push: ${{ github.event_name != 'pull_request' }}
            platforms: linux/amd64,linux/arm64
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        - run: echo ${{ steps.docker_build.outputs.digest }}